### PR TITLE
Added labels generation

### PR DESCRIPTION
**Pull request by samihormi**
* Fixes issues 
  * #2
  *  #3
  *  #7
  *  #8
  *  #11
  *  #16

### CODE REVIEW

**Review by samihormi — COMMENTED** [review]
* Fixes issues #7 #8 #11 #16

**Comment by VlSomers** [comment]
Hi @samihormi, thanks for sharing this, I will have a look asap! Have you tried to reproduce the results on one of the public datasets, such as Occluded-Duke? Do you have some visualization of the resulting masks to share?

**Comment by samihormi** [comment]
Hey @VlSomers, I did reproduce the labels for Occluded-ReID, which I used as "ground-truth", to generate masks as visually close as possible to yours. I obviously don't get the exact same masks but overall, they seem to get the job down — at least visually.
I put down some examples for your reference with my masks above and your masks below for comparison.
Also, since I guessed my way into "reverse-engineering" your approach to get the masks — using the bpbreid and PifPaf papers — there are certainly filtering steps I have omitted, please check out the code and rectify where deemed necessary.

* occluded_body_images/001/001_01.tif
output
output1

* whole_body_images/034/034_03.tif
output2
output3

* occluded_body_images/131/131_01.tif
output5
output6

**Comment by VlSomers** [comment]
Hi @samihormi , thank you for sharing these visualizations, can you update the README file and revert all the small changes you made, to only keep the added section "### Generate human parsing labels"? I will merge your PR after that

**Comment by VlSomers** [comment]
Can you also provide more information on how you choose the segmentation mask to apply? If I'm not wrong, you just pick the first one returned by maskRCNN: how do you know it is a person and not another class?

**Comment by VlSomers** [comment]
Hi @samihormi , any update about previous questions?

**Comment by samihormi** [comment]
Hey @VlSomers, yes I have changed the logic of the segmentation mask generation folllowing your comment. 

Initially, I was assuming that all input is "_human_" and I just took the first identity  generated (corresponding to the highest score). 
Now, the code filters masks to keep only humans and takes the centre-most human(x,y) as the mask — it still different from the paper but close enough.

Also, I tweaked the mask. extension of pifpaf for the  _Occluded_reID_ dataset  from ".jpg.confidence_fields.npy" to ".tif.confidence_fields.npy". which is the correct extension

**Comment by ellzeycunha0** [comment]
In get_labels.py:  The value of "filtered_masks" seems to be None because the  'cls!=0'

**Comment by samihormi** [comment]
@ellzeycunha0 Could you give me the whole error log and the dataset configuration on which you tried the code.

**Comment by ellzeycunha0** [comment]
@samihormi 
Processing:   0%|▍                                                                                                                                                                           | 225/79927 [00:14<1:09:42, 19.06batch/s]
 File "new_get_label.py", line 521, in <module>
    main()
  File "new_get_label.py", line 517, in main
    mask_model(imagery=img_paths, dataset_dir=args.source, is_overwrite=False)
  File "new_get_label.py", line 392, in __call__
    pifpaf_filtered: List[np.ndarray] = self.__filter_pifpaf_with_mask(batch, pifpaf_file_paths)
  File "new_get_label.py", line 475, in __filter_pifpaf_with_mask
    masks = filter_masks(self.model(batch))
  File "new_get_label.py", line 444, in filter_masks
    filtered_boxes, filtered_masks = zip(
ValueError: not enough values to unpack (expected 2, got 0)

"zip(...)" could be None.

**Pull request merged**
